
package ir.iais.sana.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2022-01-23T11:13:07.163+03:30
 * Generated source version: 3.3.5
 */

@WebFault(name = "AccessException", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/")
public class AccessException_Exception extends Exception {

    private AccessException accessException;

    public AccessException_Exception() {
        super();
    }

    public AccessException_Exception(String message) {
        super(message);
    }

    public AccessException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AccessException_Exception(String message, AccessException accessException) {
        super(message);
        this.accessException = accessException;
    }

    public AccessException_Exception(String message, AccessException accessException, Throwable cause) {
        super(message, cause);
        this.accessException = accessException;
    }

    public AccessException getFaultInfo() {
        return this.accessException;
    }
}
