
package ir.iais.sana.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2022-01-23T11:13:07.156+03:30
 * Generated source version: 3.3.5
 */

@WebFault(name = "DataNotFoundException", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/")
public class DataNotFoundException_Exception extends Exception {

    private DataNotFoundException dataNotFoundException;

    public DataNotFoundException_Exception() {
        super();
    }

    public DataNotFoundException_Exception(String message) {
        super(message);
    }

    public DataNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DataNotFoundException_Exception(String message, DataNotFoundException dataNotFoundException) {
        super(message);
        this.dataNotFoundException = dataNotFoundException;
    }

    public DataNotFoundException_Exception(String message, DataNotFoundException dataNotFoundException, Throwable cause) {
        super(message, cause);
        this.dataNotFoundException = dataNotFoundException;
    }

    public DataNotFoundException getFaultInfo() {
        return this.dataNotFoundException;
    }
}
