
package ir.iais.sana.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2022-01-23T11:13:07.168+03:30
 * Generated source version: 3.3.5
 */

@WebFault(name = "MisMatchNationalCodeException", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/")
public class MisMatchNationalCodeException_Exception extends Exception {

    private MisMatchNationalCodeException misMatchNationalCodeException;

    public MisMatchNationalCodeException_Exception() {
        super();
    }

    public MisMatchNationalCodeException_Exception(String message) {
        super(message);
    }

    public MisMatchNationalCodeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MisMatchNationalCodeException_Exception(String message, MisMatchNationalCodeException misMatchNationalCodeException) {
        super(message);
        this.misMatchNationalCodeException = misMatchNationalCodeException;
    }

    public MisMatchNationalCodeException_Exception(String message, MisMatchNationalCodeException misMatchNationalCodeException, Throwable cause) {
        super(message, cause);
        this.misMatchNationalCodeException = misMatchNationalCodeException;
    }

    public MisMatchNationalCodeException getFaultInfo() {
        return this.misMatchNationalCodeException;
    }
}
