
package ir.iais.sana.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2022-01-23T11:13:07.166+03:30
 * Generated source version: 3.3.5
 */

@WebFault(name = "OpenSanaInfoExistException", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/")
public class OpenSanaInfoExistException_Exception extends Exception {

    private OpenSanaInfoExistException openSanaInfoExistException;

    public OpenSanaInfoExistException_Exception() {
        super();
    }

    public OpenSanaInfoExistException_Exception(String message) {
        super(message);
    }

    public OpenSanaInfoExistException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public OpenSanaInfoExistException_Exception(String message, OpenSanaInfoExistException openSanaInfoExistException) {
        super(message);
        this.openSanaInfoExistException = openSanaInfoExistException;
    }

    public OpenSanaInfoExistException_Exception(String message, OpenSanaInfoExistException openSanaInfoExistException, Throwable cause) {
        super(message, cause);
        this.openSanaInfoExistException = openSanaInfoExistException;
    }

    public OpenSanaInfoExistException getFaultInfo() {
        return this.openSanaInfoExistException;
    }
}
