package ir.iais.sana.services;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2022-01-23T11:13:07.186+03:30
 * Generated source version: 3.3.5
 */
@WebServiceClient(name = "PushSanaV5Service",
        wsdlLocation = "/PushSanaV5.wsdl",
        targetNamespace = "http://servicebus.sana.ir/PushSana/v5/")
public class PushSanaV5Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicebus.sana.ir/PushSana/v5/", "PushSanaV5Service");
    public final static QName PushSanaV5Port = new QName("http://servicebus.sana.ir/PushSana/v5/", "PushSanaV5Port");

    static {
        WSDL_LOCATION = PushSanaV5Service.class.getResource("/PushSanaV5.wsdl");
    }

    public PushSanaV5Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PushSanaV5Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PushSanaV5Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PushSanaV5Service(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PushSanaV5Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PushSanaV5Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns PushSanaV5
     */
    @WebEndpoint(name = "PushSanaV5Port")
    public PushSanaV5 getPushSanaV5Port() {
        return super.getPort(PushSanaV5Port, PushSanaV5.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns PushSanaV5
     */
    @WebEndpoint(name = "PushSanaV5Port")
    public PushSanaV5 getPushSanaV5Port(WebServiceFeature... features) {
        return super.getPort(PushSanaV5Port, PushSanaV5.class, features);
    }

}
