package ir.iais.sana.services;

import ir.iais.sana.domain.sana.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2022-01-24T15:29:39.784+03:30
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", name = "PushSanaV5")
@XmlSeeAlso({ObjectFactory.class})
public interface PushSanaV5 {

    @WebMethod
    @RequestWrapper(localName = "sendIncomes", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendIncomes")
    @ResponseWrapper(localName = "sendIncomesResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendIncomesResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendIncomes(

        @WebParam(name = "incomes", targetNamespace = "")
        java.util.List<Income> incomes,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendPrograms", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendPrograms")
    @ResponseWrapper(localName = "sendProgramsResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendProgramsResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendPrograms(

        @WebParam(name = "programs", targetNamespace = "")
        java.util.List<Program> programs,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getRequestsStatus", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.GetRequestsStatus")
    @ResponseWrapper(localName = "getRequestsStatusResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.GetRequestsStatusResponse")
    @WebResult(name = "sanaRequestStatus", targetNamespace = "")
    public java.util.List<SanaRequestStatus> getRequestsStatus()
 throws InternalServerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendAccGroupsCodeList", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendAccGroupsCodeList")
    @ResponseWrapper(localName = "sendAccGroupsCodeListResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendAccGroupsCodeListResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendAccGroupsCodeList(

        @WebParam(name = "accGroupsCodes", targetNamespace = "")
        java.util.List<AccGroupsCode> accGroupsCodes,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendCostCenters", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendCostCenters")
    @ResponseWrapper(localName = "sendCostCentersResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendCostCentersResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendCostCenters(

        @WebParam(name = "costCenters", targetNamespace = "")
        java.util.List<CostCenter> costCenters,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cancelRequest", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.CancelRequest")
    @ResponseWrapper(localName = "cancelRequestResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.CancelRequestResponse")
    public void cancelRequest(

        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendOrganizations", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendOrganizations")
    @ResponseWrapper(localName = "sendOrganizationsResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendOrganizationsResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendOrganizations(

        @WebParam(name = "organizations", targetNamespace = "")
        java.util.List<Organization> organizations,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendGeneralAccCodes", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendGeneralAccCodes")
    @ResponseWrapper(localName = "sendGeneralAccCodesResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendGeneralAccCodesResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendGeneralAccCodes(

        @WebParam(name = "generalAccCodes", targetNamespace = "")
        java.util.List<GeneralAccCode> generalAccCodes,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendProjects", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendProjects")
    @ResponseWrapper(localName = "sendProjectsResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendProjectsResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendProjects(

        @WebParam(name = "projects", targetNamespace = "")
        java.util.List<Project> projects,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendBankAccounts", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendBankAccounts")
    @ResponseWrapper(localName = "sendBankAccountsResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendBankAccountsResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendBankAccounts(

        @WebParam(name = "bankAccounts", targetNamespace = "")
        java.util.List<BankAccount> bankAccounts,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod(operationName = "sendDetailedAccCode1s")
    @RequestWrapper(localName = "sendDetailedAccCode1s", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode1S")
    @ResponseWrapper(localName = "sendDetailedAccCode1sResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode1SResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendDetailedAccCode1S(

        @WebParam(name = "detailedAccCode1s", targetNamespace = "")
        java.util.List<DetailedAccCode1> detailedAccCode1S,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendPlans", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendPlans")
    @ResponseWrapper(localName = "sendPlansResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendPlansResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendPlans(

        @WebParam(name = "plans", targetNamespace = "")
        java.util.List<Plan> plans,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "reserveSanaInfo", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.ReserveSanaInfo")
    @ResponseWrapper(localName = "reserveSanaInfoResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.ReserveSanaInfoResponse")
    @WebResult(name = "sanaId", targetNamespace = "")
    public long reserveSanaInfo(

        @WebParam(name = "protocolId", targetNamespace = "")
       ProtocolId protocolId
    ) throws OpenSanaInfoExistException_Exception, InternalServerException_Exception, MisMatchNationalCodeException_Exception;

    @WebMethod(operationName = "sendDetailedAccCode2s")
    @RequestWrapper(localName = "sendDetailedAccCode2s", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode2S")
    @ResponseWrapper(localName = "sendDetailedAccCode2sResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode2SResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendDetailedAccCode2S(

        @WebParam(name = "detailedAccCode2s", targetNamespace = "")
        java.util.List<DetailedAccCode2> detailedAccCode2S,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod(operationName = "sendDetailedAccCode3s")
    @RequestWrapper(localName = "sendDetailedAccCode3s", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode3S")
    @ResponseWrapper(localName = "sendDetailedAccCode3sResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode3SResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendDetailedAccCode3S(

        @WebParam(name = "detailedAccCode3s", targetNamespace = "")
        java.util.List<DetailedAccCode3> detailedAccCode3S,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod(operationName = "sendDetailedAccCode4s")
    @RequestWrapper(localName = "sendDetailedAccCode4s", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode4S")
    @ResponseWrapper(localName = "sendDetailedAccCode4sResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode4SResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendDetailedAccCode4S(

        @WebParam(name = "detailedAccCode4s", targetNamespace = "")
        java.util.List<DetailedAccCode4> detailedAccCode4S,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod(operationName = "sendDetailedAccCode5s")
    @RequestWrapper(localName = "sendDetailedAccCode5s", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode5S")
    @ResponseWrapper(localName = "sendDetailedAccCode5sResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendDetailedAccCode5SResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendDetailedAccCode5S(

        @WebParam(name = "detailedAccCode5s", targetNamespace = "")
        java.util.List<DetailedAccCode5> detailedAccCode5S,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "finishRequest", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.FinishRequest")
    @ResponseWrapper(localName = "finishRequestResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.FinishRequestResponse")
    public void finishRequest(

        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendAccountFlows", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendAccountFlows")
    @ResponseWrapper(localName = "sendAccountFlowsResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendAccountFlowsResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendAccountFlows(

        @WebParam(name = "accountFlows", targetNamespace = "")
        java.util.List<AccountFlow> accountFlows,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendLedgerAccCodes", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendLedgerAccCodes")
    @ResponseWrapper(localName = "sendLedgerAccCodesResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendLedgerAccCodesResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendLedgerAccCodes(

        @WebParam(name = "ledgerAccCodes", targetNamespace = "")
        java.util.List<LedgerAccCode> ledgerAccCodes,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;

    @WebMethod
    @RequestWrapper(localName = "sendAccVouchers", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendAccVouchers")
    @ResponseWrapper(localName = "sendAccVouchersResponse", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/", className = "ir.iais.sana.services.SendAccVouchersResponse")
    @WebResult(name = "count", targetNamespace = "")
    public long sendAccVouchers(

        @WebParam(name = "accVouchers", targetNamespace = "")
        java.util.List<AccVoucher> accVouchers,
        @WebParam(name = "sanaId", targetNamespace = "")
        java.lang.Long sanaId
    ) throws InternalServerException_Exception, DataNotFoundException_Exception, RequestNotOpenException_Exception, AccessException_Exception;
}
