
package ir.iais.sana.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2022-01-23T11:13:07.160+03:30
 * Generated source version: 3.3.5
 */

@WebFault(name = "RequestNotOpenException", targetNamespace = "http://servicebus.sana.ir/PushSana/v5/")
public class RequestNotOpenException_Exception extends Exception {

    private RequestNotOpenException requestNotOpenException;

    public RequestNotOpenException_Exception() {
        super();
    }

    public RequestNotOpenException_Exception(String message) {
        super(message);
    }

    public RequestNotOpenException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RequestNotOpenException_Exception(String message, RequestNotOpenException requestNotOpenException) {
        super(message);
        this.requestNotOpenException = requestNotOpenException;
    }

    public RequestNotOpenException_Exception(String message, RequestNotOpenException requestNotOpenException, Throwable cause) {
        super(message, cause);
        this.requestNotOpenException = requestNotOpenException;
    }

    public RequestNotOpenException getFaultInfo() {
        return this.requestNotOpenException;
    }
}
